#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

var out = process.stdout;

function print(message) {
 process.stdout.write(message);
}


print(c.clear + c.multi("Welcome to the magic eightball") + "\n");
