#!/usr/bin/env python3 

import skilstak.colors as c

from time import sleep

while True:
    print(c.clear + c.multi("Welcome to the magic eightball")) 
    sleep(1)

answers = [
 'No.',
 'Yes.',
 'Maybe.',
 'Never.',
 'IDK.',
 'There is a chance.'
]

easter_eggs = [
    ["death|die", "I can not predict death"],
    ["love", "That is beyond my abilities"]
]

